## Environment variables template
# DB_NAME: postgres 
# DB_USER: postgres 
# DB_PASSWORD: postgres 
#
#
## Backend
# DOCKPLOY_BACKEND_HOST: backend.presentationlab.org 
# DEBUG: False 
# 
# SECRET_KEY: random-secret-key-*$&*#@!HDU@D&*@$G@!*&H*D&H& 
# ALLOWED_HOSTS: backend.presentationlab.org,frontend.presentationlab 
# CSRF_TRUSTED_ORIGINS: https://backend.presentationlab.org, https://frontend.presentationlab.org 
# CORS_ALLOWED_ORIGINS: https://backend.presentationlab.org, https://frontend.presentationlab.org 
#
## Frontend
# DOCKPLOY_FRONTEND_HOST: frontend.presentationlab.org 
# VITE_API_URL: https://backend.presentationlab.org 
#



services:
  # PostgreSQL Database
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    # Remove fixed port mapping for production deployment
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend API
  backend:
    build:
      context: ./django-rest-api
      dockerfile: Dockerfile
    restart: unless-stopped
    # Use expose instead of ports for Dokploy compatibility
    args:
      - DEBUG=${DEBUG}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python wait-for-db.py &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py create_default_superuser &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network
    labels:
      - "dokploy.main-service=backend"
      # Traefik labels for production routing
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.presentationlab.org`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  # React Frontend
  frontend:
    build:
      context: ./react-shadcn-ui
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=https://backend.presentationlab.org
    restart: unless-stopped
    # Use expose instead of ports for Dokploy compatibility
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - app-network
    labels:
      - "dokploy.frontend=true"
      # Traefik labels for production routing
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.presentationlab.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
