services:
  # PostgreSQL Database
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    # No external port mapping - internal communication only
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend API
  backend:
    build:
      context: ./django-rest-api
      dockerfile: Dockerfile
    restart: unless-stopped
    # Dokploy will handle external port mapping
    expose:
      - "8000"
    environment:
      - DEBUG=${DEBUG:-0}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - dokploy-network
    command: >
      sh -c "python wait-for-db.py &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py create_default_superuser &&
             python manage.py runserver 0.0.0.0:8000"
    labels:
      - "dokploy.backend=true"
      - "dokploy.main-service=true"
      # Traefik labels for production routing
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.presentationlab.org`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  # React Frontend
  frontend:
    build:
      context: ./react-shadcn-ui
      dockerfile: Dockerfile
    restart: unless-stopped
    # Dokploy will handle external port mapping
    expose:
      - "3000"
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://backend.presentationlab.org}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      - dokploy-network
    labels:
      - "dokploy.frontend=true"
      # Traefik labels for production routing
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.presentationlab.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  dokploy-network:
    external: true