#### register a user
POST http://127.0.0.1:8000/api/user/register/
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

#### Production
POST http://127.0.0.1:8000/api/user/token/
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
